<?xml version="1.0" encoding="UTF-8" ?>
<testsuites>
  <testsuite errors="0" failures="1" hostname="Rogerios-MacBook-Pro.local" id="0" name="NinjaTests" package="org.example" tests="1" time="1.368" timestamp="2016-02-03T22:21:53">
      <properties />

      <testcase classname="org.example.NinjaTests" name="testSomething" time="1.329">
          <failure message="Assertion failed: &#xa;&#xa;assert instance.hasErrors()&#xa;       |        |&#xa;       |        false&#xa;       org.example.Ninja : (unsaved)&#xa;" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: Assertion failed: 

assert instance.hasErrors()
       |        |
       |        false
       org.example.Ninja : (unsaved)

	at org.example.NinjaTests.testSomething(NinjaTests.groovy:12)
</failure>

      </testcase>

      <system-out><![CDATA[--Output from testSomething--
]]></system-out>

      <system-err><![CDATA[--Output from testSomething--
]]></system-err>

  </testsuite>
</testsuites>
